# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: cirrusci/flutter:beta-web

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      # grant github folder privilege to cirrus user
    - name: chmod
      run: |
        sudo chmod -R 777 $HOME
        sudo chmod -R 777 $GITHUB_WORKSPACE
        
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
      
    - name: install
      run: |
        npm ci
        flutter config --enable-web
        flutter packages get
    
    - name: lint
      run: |
        flutter format --set-exit-if-changed lib
        flutter analyze lib
    
    - name: build
      run: npm run build --if-present
    
    - name: test
      run: npm test
